name: Cache Action
on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: 0 0 * * * # Every day at 00:00

jobs:
  update-assets:
    runs-on: ubuntu-latest
    steps:
      # Checkout with custom token for push to protected branch
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download stats.svg
        run: |
          mkdir -p assets
          curl 'https://github-readme-stats-99ejj06al-ossan-engineer.vercel.app/api?username=ossan-engineer&show_icons=true&count_private=true' -o assets/stats.svg

      - name: Push stats.svg
        run: |
          git config user.name "ossan-engineer"
          git config user.email "bodega1123@gmail.com"
          git add assets/stats.svg
          git commit -i assets/stats.svg -m "[skip ci] Update assets"
          git push origin
