# .github/workflows/ping-vercel.yml
name: Ping Vercel to prevent cold start

on:
  schedule:
    - cron: '*/15 * * * *' # 15分ごとに実行

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl your Vercel app
        run: curl -s https://github-readme-stats-99ejj06al-ossan-engineer.vercel.app/api?username=ossan-engineer > /dev/null
